service: email-service

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]
  environment:
    DESIRED_RECIPIENT: ${ssm:myEmail} # Pulls from local ssm, you can replace it with your AWS validated email

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  sendMail:
    handler: bin/sendMail
    events:
      - http:
          path: sendMail
          method: post
          cors: true